### ISSUE TITLE
Issues with version 2

### ISSUE THREAD

**Issue by mwtoews** [mullenkamp/hilltop-py#71]
Since version 2 development from #51, I'm seeing a few issues that were not present before.

For example take this example:
```python
import hilltoppy.web_service

base_url = "https://data.hbrc.govt.nz/Envirodata"
hts = "ContinuousArchive.hts"
site = "Well.MW2s Brookvale Road"
meas = "Elevation Above Sea Level [Recorder Water Level]"
ts_df = hilltoppy.web_service.get_data(
    base_url, hts, site, meas,
    agg_method="Average",
    agg_interval="1 week")
```

With d61b18f48214cb89cf3149dd4fbdd4ca2b3c96d8 from Windows with conda-forge installed dependencies the output is:
```
C:\Users\mtoews\AppData\Local\miniforge3\envs\pyforge\lib\site-packages\pydantic\_internal\_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'json_dumps' has been removed
* 'json_loads' has been removed
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "D:\src\hilltop-py\trythis.py", line 7, in <module>
    ts_df = hilltoppy.web_service.get_data(
  File "D:\src\hilltop-py\hilltoppy\web_service.py", line 396, in get_data
    ds_dict1 = orjson.loads(DataSource(**ds_dict).json(exclude_none=True))
  File "C:\Users\mtoews\AppData\Local\miniforge3\envs\pyforge\lib\site-packages\pydantic\main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for DataSource
Interpolation
  Input should be 'Discrete','Instant','Incremental' or 'Event' [type=enum, input_value='Histogram', input_type=str]
```
and a variation on the above `get_data` example without `agg_*` methods shows a different error:
```
C:\Users\mtoews\AppData\Local\miniforge3\envs\pyforge\lib\site-packages\pydantic\_internal\_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'json_dumps' has been removed
* 'json_loads' has been removed
  warnings.warn(message, UserWarning)
D:\src\hilltop-py\hilltoppy\utils.py:193: UserWarning: Parsing dates in %Y-%m-%dT%H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  val = pd.to_datetime(val, dayfirst=True)
Traceback (most recent call last):
  File "D:\src\hilltop-py\trythis.py", line 7, in <module>
    ts_df = hilltoppy.web_service.get_data(
  File "D:\src\hilltop-py\hilltoppy\web_service.py", line 443, in get_data
    if m['MeasurementName'].lower() == measurement.lower():
TypeError: string indices must be integers
```
Same issues are found on Linux with pip installed dependences.

**Comment by mullenkamp** [comment]
Both your last issue and this issue is likely due to both Pandas and Pydantic upgrading to a new full version (version 2 on both coincidentally). They both have made breaking changes (Pydantic is particularly bad...). I've changed a few of my packages already to more narrowly define the version dependencies, but I haven't got around to all of them. I'll fix this up soon, but in the short term, you just need to install the latest versions of version 1 for both Pandas and Pydantic.

**Comment by mullenkamp** [comment]
Fixed by specifying pydantic >2 in the package deps
#72
